### ISSUE TITLE
running for 10 minutes and then all other cameras go offline

### ISSUE THREAD

**Issue by fparrav** [p10tyr/rtsp-to-onvif#25]
I'm currently running a build compiled for arm64 since the original image didn't have raspberry support. Since I'm using raspbian I had to generate different ports for each camera, but they work almost perfectly for about 10 minutes or more, if I stop docker comoose and start it again I get the connection back. If I check the logs I don't see any disconnection message.

My configuration file:

```

onvif:
  - name: Dafang
    dev: eth0
    target:
      hostname: 192.168.20.32
      ports:
        rtsp: 554
        snapshot: 443
    highQuality:
      rtsp: /unicast
      snapshot: /cgi-bin/currentpic.cgi
      width: 1280
      height: 720
      framerate: 25
      bitrate: 2048
      quality: 4
    ports:
      server: 8081
      rtsp: 8554
      snapshot: 8080
    uuid: d48b061e-4151-42a7-b309-084245e31630
    mac: 1A:11:B0:1F:17:13
  - name: Logia
    dev: eth0
    target:
      hostname: 192.168.20.193
      ports:
        rtsp: 554
        snapshot: 443
    highQuality:
      rtsp: /live0
      snapshot: /live0
      width: 1920
      height: 1080
      framerate: 15
      bitrate: 2048
      quality: 4
    ports:
      server: 8091
      rtsp: 8555
      snapshot: 8090
    uuid: 444583e2-4c2f-4706-b693-e7e4589bae8f
    mac: 1A:11:B0:FF:F1:95
  - name: Patio
    dev: eth0
    target:
      hostname: 192.168.20.103
      ports:
        rtsp: 554
        snapshot: 443
    highQuality:
      rtsp: /live0
      snapshot: /live0
      width: 1920
      height: 1080
      framerate: 15
      bitrate: 2048
      quality: 4
    ports:
      server: 8094
      rtsp: 8559
      snapshot: 8095
    uuid: 474a98dd-995f-4538-a5fb-09e6bc2fc627
    mac: 1A:11:B0:F3:BF:99
  - name: Entrada
    dev: eth0
    target:
      hostname: 192.168.20.118
      ports:
        rtsp: 554
        snapshot: 443
    highQuality:
      rtsp: /live0
      snapshot: /live0
      width: 1920
      height: 1080
      framerate: 15
      bitrate: 2048
      quality: 4
    ports:
      server: 8093
      rtsp: 8557
      snapshot: 8092
    uuid: 21a7032c-bd6d-4859-a87f-ef92df8fc5c2
    mac: 1A:11:B0:73:B5:95
  - name: Dormitorio
    dev: eth0
    target:
      hostname: 192.168.20.35
      ports:
        rtsp: 554
        snapshot: 443
    highQuality:
      rtsp: /live0
      snapshot: /live0
      width: 1920
      height: 1080
      framerate: 15
      bitrate: 2048
      quality: 4
    ports:
      server: 8096
      rtsp: 8560
      snapshot: 8097
    uuid: 4fb71f11-fbbb-4413-b701-eebe2d178301
    mac: 1A:11:B0:55:FD:75

```
