### ISSUE TITLE
ARM Docker Images

### ISSUE THREAD

**Issue by TotalGriffLock** [p10tyr/rtsp-to-onvif#33]
It would be great if you could publish arm docker images for this, so it can be run on a raspberry pi, lower spec nas devices, etc.

build_docker.sh works perfectly on my rpi5 which is armv8, FYI, so people who need this on such hardware can run

```
git clone https://github.com/p10tyr/rtsp-to-onvif
sudo ./build-docker.sh
```

This will build the current github version of the docker image into your local docker image library, so you can then use docker compose. You'd need to rerun it to apply updates.

**Comment by tablatronix** [comment]
Ditto, It would be nice to have real multiarch builds

**Comment by jozefmutis** [comment]
Ditto, x86, amd64 and armv7+ builds are a given nowadays.

**Comment by rveachkc** [comment]
This is a version of the compose I'm using, where I've simply cloned this repo into the relative `app` directory.

It looks like you can also add a git url, but I didn't want to pick up any updates without a heads up

```yaml
services:
  rtsp-to-onvif:
    container_name: rtsp-to-onvif
    # image: kulasolutions/rtsp-to-onvif:latest
    build:
      context: ./app
      dockerfile: Dockerfile
    hostname: rtsp-to-onvif
    #restart: unless-stopped
    volumes:
      - ./config.yaml:/onvif.yaml
    network_mode: "host"   
    cap_add:
      - NET_ADMIN
    environment: # uncomment this to get more debug info during setup
      DEBUG: 1
```
